### ISSUE TITLE
🔨 refactor: API 함수명 + TanStack Query 함수명 통일

### ISSUE THREAD

**Issue by imssein** [prgrms-fe-devcourse/FEDC5_jackpot_letter_Donguk#109]
# 📌 작업 내용

[노션 페이지](https://www.notion.so/prgrms/API-099c249ebbb94de5935e799c204a227e?pvs=4) 참고해주세요!!

**Comment by moyukyung** [comment]
<img width="823" alt="스크린샷 2024-01-12 오후 2 07 59" src="https://github.com/prgrms-fe-devcourse/FEDC5_jackpot_letter_Donguk/assets/75975946/5dc8fa1e-4140-4327-a1fc-a1554ff6f74d">

알림 확인 처리의 경우에는 한번에 여러개의 알림을 확인 처리하고, 알림 생성의 경우에는 한번에 하나의 알림을 생성하는데, 각각 checkNotifications, createNotification으로 수정해도 괜찮을까요?!
